//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_JCG3AbozEdyoutuWGu0opAActivity"]="./../../practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/resources/pre_sale_solution_design_5F4EC164_5f4ec164_Activity.jpeg"
contentPage.processPage.imageFiles["_JCG3AbozEdyoutuWGu0opA,_lh6Qgb1JEdyrVscmNb_pGwActivityDetail"]="./../../practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/resources/develop_and_agree_to_client_solution_5909977E_8b87fb36_ActivityDetail.jpeg"
contentPage.processPage.suppressedItems["_JCG3AbozEdyoutuWGu0opA,_lh6Qgb1JEdyrVscmNb_pGw,_izFiIDnIEeWSlKMT0LW-Gg"]=true
contentPage.processPage.imageFiles["_JCG3AbozEdyoutuWGu0opA,_MlRwob1FEdyrVscmNb_pGwActivityDetail"]="./../../practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/resources/explore_options_and_approach_DB5B313F_dd994f7_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_VuARsI8lEd2tn4QxorRg1Q,_f4FaYekLEd-IPpFA2ds-HAActivityDetail"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/develop_and_agree_to_client_solution_54C3D910_4ad4a9f0_ActivityDetail.jpeg"
contentPage.processPage.suppressedItems["_r0U7sb1HEdyrVscmNb_pGw,_VuARsI8lEd2tn4QxorRg1Q,_f4FaYekLEd-IPpFA2ds-HA,_izFiIDnIEeWSlKMT0LW-Gg"]=true
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_VuARsI8lEd2tn4QxorRg1Q,_e9hPkekLEd-IPpFA2ds-HAActivityDetail"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/explore_options_and_approach_FAAACAF1_f0bb9bd1_ActivityDetail.jpeg"
contentPage.processPage.suppressedItems["_r0U7sb1HEdyrVscmNb_pGw,_VuARsI8lEd2tn4QxorRg1Q,_e9hPkekLEd-IPpFA2ds-HA,_cPi9sN5NEdy-jeg0wYuB9Q"]=true
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_xSqMob1HEdyrVscmNb_pGwActivity"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/plan_3B3D50B4_c51733e1_Activity.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_B-6ukb1IEdyrVscmNb_pGw,_-hTFQb1UEdyrVscmNb_pGwActivityDetail"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/implement_client_solution.teamethod_84A9B855_d0e490e2_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_B-6ukb1IEdyrVscmNb_pGwActivity"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/support_impl_and_confirm_value.teamsd_43A420C_8e142539_Activity.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_xSqMob1HEdyrVscmNb_pGw,_x09L971IEdyrVscmNb_pGwActivityDetail"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/understand_clients_business_and_needs.teamsd_5FCFE714_2df65649_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGwActivity"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/teamsd_6B210FD9_6b210fd9_Activity.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_B-6ukb1IEdyrVscmNb_pGw,_FFz7Ib1VEdyrVscmNb_pGwActivityDetail"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/confirm_client_value_and_experience.teamethod_85BEC7CE_d1f9a05b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_r0U7sb1HEdyrVscmNb_pGw,_VuARsI8lEd2tn4QxorRg1QActivity"]="./../../process.tech.teamsd.base-ibm_int/deliveryprocesses/resources/team_soln_dsgn_pre_sale_solution_design_421A435F_cbf4268c_Activity.jpeg"
contentPage.processPage.elementUrls["_geotcL1VEdyrVscmNb_pGw"] = ["Explore New Client Issues","process.tech.teamsd.base-ibm_int/deliveryprocesses/explore_new_client_issues_795E88E4.html"];
contentPage.processPage.elementUrls["_C3b7YN5MEdy-jeg0wYuB9Q"] = ["Business Direction","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/business_direction_C795266F.html"];
contentPage.processPage.elementUrls["_WJHdkcXREeaaG61gY1NekQ"] = ["Node","process.tech.teamsd.base-ibm_int/deliveryprocesses/node_28EAB83A.html"];
contentPage.processPage.elementUrls["_Xns0p92kEdy-jeg0wYuB9Q"] = ["Current Organization Description","process.tech.teamsd.base-ibm_int/deliveryprocesses/current_org_description_68118EF2.html"];
contentPage.processPage.elementUrls["_-hTFQb1UEdyrVscmNb_pGw"] = ["IMPLEMENT Client Solution","process.tech.teamsd.base-ibm_int/deliveryprocesses/implement_client_solution.teamethod_84A9B855.html"];
contentPage.processPage.elementUrls["_EZkfQQD4Ed2JMcEzMiB9RQ"] = ["Requirements Matrix","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/rqmts_matrix_4002653.html"];
contentPage.processPage.elementUrls["_GZNWIPBtEdyQkoYzAyZ7Vg"] = ["Requirements Matrix","process.tech.teamsd.base-ibm_int/deliveryprocesses/rqmts_matrix_D7986856.html"];
contentPage.processPage.elementUrls["_gBZqIcEXEea7yN6m1uQOEw"] = ["Node Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/node_model_5CFD9954.html"];
contentPage.processPage.elementUrls["_7Gy9sb0zEealzs-Z6MLRQg"] = ["Actor","process.tech.teamsd.base-ibm_int/deliveryprocesses/actor_7784F90C.html"];
contentPage.processPage.elementUrls["_JCG3AbozEdyoutuWGu0opA"] = ["Pre-sale Solution Design","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/pre_sale_solution_design_5F4EC164.html"];
contentPage.processPage.elementUrls["_8To2cMLcEdyILIjfj0O0vQ"] = ["Opportunity Validated","process.tech.teamsd.base-ibm_int/deliveryprocesses/opportunity_validated_710EB0C9.html"];
contentPage.processPage.elementUrls["_Xns0rd2kEdy-jeg0wYuB9Q"] = ["Viability Assessment","process.tech.teamsd.base-ibm_int/deliveryprocesses/viability_assessment_7DBD9D5B.html"];
contentPage.processPage.elementUrls["_x09L971IEdyrVscmNb_pGw"] = ["UNDERSTAND Client\'s Business and Needs","process.tech.teamsd.base-ibm_int/deliveryprocesses/understand_clients_business_and_needs.teamsd_5FCFE714.html"];
contentPage.processPage.elementUrls["_gBS8ccEXEea7yN6m1uQOEw"] = ["Use Case","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/use_case_3371EFE8.html"];
contentPage.processPage.elementUrls["_31BYUr1FEdyrVscmNb_pGw"] = ["Identify Non-Functional Requirements","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/identify_non_functional_requirements_CA3DB6BA.html"];
contentPage.processPage.elementUrls["_q_Wx0MfZEd6U27gReX5GsQ"] = ["Use-Case Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/use_case_model_66D0C870.html"];
contentPage.processPage.elementUrls["_8PO0UN53Edy-jeg0wYuB9Q"] = ["Viability Assessment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/viability_assessment_69EE08CD.html"];
contentPage.processPage.elementUrls["_WJFBUcXREeaaG61gY1NekQ"] = ["Location Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/location_model_247CA130.html"];
contentPage.processPage.elementUrls["_x09L9L1IEdyrVscmNb_pGw"] = ["Standards","process.tech.teamsd.base-ibm_int/deliveryprocesses/standards_FDBF1D29.html"];
contentPage.processPage.elementUrls["_8ltV4f4jEeSlbqNAhOaBVQ"] = ["Enterprise Architect","process.tech.teamsd.base-ibm_int/deliveryprocesses/enterprise_architect_757C01BB.html"];
contentPage.processPage.elementUrls["_C3SKYN5MEdy-jeg0wYuB9Q"] = ["Viability Assessment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/viability_assessment_466939F2.html"];
contentPage.processPage.elementUrls["_ffvQUGEBEd6dM5yVkA6IKQ"] = ["Client Value Account Plan","process.tech.teamsd.base-ibm_int/deliveryprocesses/client_value_account_plan_32A3824A.html"];
contentPage.processPage.elementUrls["_sQSpQDMXEd2ljpuQizMR7w"] = ["Identify and Outline Requirements","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/identify_outline_rqmts_B4BEF749.html"];
contentPage.processPage.elementUrls["_Xocbgd2kEdy-jeg0wYuB9Q"] = ["Viability Assessment","process.tech.teamsd.base-ibm_int/deliveryprocesses/viability_assessment_C93B8D49.html"];
contentPage.processPage.elementUrls["_dJ9tIb1UEdyrVscmNb_pGw"] = ["System Context","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/system_context_5374EF11.html"];
contentPage.processPage.elementUrls["_gBABhMEXEea7yN6m1uQOEw"] = ["Service Specification","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_specification_DAF90549.html"];
contentPage.processPage.elementUrls["_Xocbgt2kEdy-jeg0wYuB9Q"] = ["Architectural Decisions","process.tech.teamsd.base-ibm_int/deliveryprocesses/architectural_decisions_D3D96D59.html"];
contentPage.processPage.elementUrls["_Xns0qN2kEdy-jeg0wYuB9Q"] = ["Non-Functional Requirements","process.tech.teamsd.base-ibm_int/deliveryprocesses/nonfunctional_requirements_CA92A726.html"];
contentPage.processPage.elementUrls["_gBctccEXEea7yN6m1uQOEw"] = ["Connection","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/connection_E17E3F14.html"];
contentPage.processPage.elementUrls["_Xns0q92kEdy-jeg0wYuB9Q"] = ["System Context","process.tech.teamsd.base-ibm_int/deliveryprocesses/system_context_2CA37111.html"];
contentPage.processPage.elementUrls["_8ltV4v4jEeSlbqNAhOaBVQ"] = ["Technical Account Plan","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_account_plan_8019E1CB.html"];
contentPage.processPage.elementUrls["_B-6ukb1IEdyrVscmNb_pGw"] = ["Support Implementation and Confirm Value","process.tech.teamsd.base-ibm_int/deliveryprocesses/support_impl_and_confirm_value.teamsd_43A420C.html"];
contentPage.processPage.elementUrls["_dgKokMLkEdyILIjfj0O0vQ"] = ["Value Confirmed","process.tech.teamsd.base-ibm_int/deliveryprocesses/value_confirmed_E1A68551.html"];
contentPage.processPage.elementUrls["_tzTooP4PEeSYqfYP0mAopw"] = ["Design Professional","process.tech.teamsd.base-ibm_int/deliveryprocesses/design_professional_23EEA701.html"];
contentPage.processPage.elementUrls["_cPi9sN5NEdy-jeg0wYuB9Q"] = ["Define Project","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/define_project_470E4B6E.html"];
contentPage.processPage.elementUrls["_gBZDEcEXEea7yN6m1uQOEw"] = ["Location Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/location_model_23C2E1EB.html"];
contentPage.processPage.elementUrls["_8ltV4P4jEeSlbqNAhOaBVQ"] = ["Plan for Client Value","process.tech.teamsd.base-ibm_int/deliveryprocesses/plan_for_client_value_86E2EDA5.html"];
contentPage.processPage.elementUrls["_1jurIL1FEdyrVscmNb_pGw"] = ["Describe System Context","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/describe_system_context_96149E61.html"];
contentPage.processPage.elementUrls["_EZkfQAD4Ed2JMcEzMiB9RQ"] = ["Identify High Level Data Sources","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/identify_high_level_data_sources_F9624643.html"];
contentPage.processPage.elementUrls["_YyNEQN_mEdy-jeg0wYuB9Q"] = ["Technical Solution Architect","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_solution_architect_85F883F.html"];
contentPage.processPage.elementUrls["_zbqW4AwdEeSQgZ4v5FkZyw"] = ["Candidate Asset List","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/candidate_asset_list_D0B1EAF8.html"];
contentPage.processPage.elementUrls["_1jurIr1FEdyrVscmNb_pGw"] = ["System Context","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/system_context_8F4B9287.html"];
contentPage.processPage.elementUrls["_LX0VkYs2Ed2OXeRvRIcs3A"] = ["Current Organization Description","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/current_org_description_978853E0.html"];
contentPage.processPage.elementUrls["_fwfgUcEXEea7yN6m1uQOEw"] = ["Component Specification","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/component_specification_7BE786C8.html"];
contentPage.processPage.elementUrls["_31BYVb1FEdyrVscmNb_pGw"] = ["Non-Functional Requirements","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/nonfunctional_requirements_8431B8C9.html"];
contentPage.processPage.elementUrls["_dJ9tIL1UEdyrVscmNb_pGw"] = ["Develop High Level Component Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/develop_high_level_component_model_64DBDAFB.html"];
contentPage.processPage.elementUrls["_Xns0o92kEdy-jeg0wYuB9Q"] = ["Business Direction","process.tech.teamsd.base-ibm_int/deliveryprocesses/business_direction_A37FACD3.html"];
contentPage.processPage.elementUrls["_Y2hjkN_mEdy-jeg0wYuB9Q"] = ["Technical Solution Architect","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_solution_architect_C0D44F29.html"];
contentPage.processPage.elementUrls["_dJ9tIr1UEdyrVscmNb_pGw"] = ["Component Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/component_model_5E12CF21.html"];
contentPage.processPage.elementUrls["_WJAI0cXREeaaG61gY1NekQ"] = ["Component Specification","process.tech.teamsd.base-ibm_int/deliveryprocesses/component_specification_D4E66F21.html"];
contentPage.processPage.elementUrls["_gBABgcEXEea7yN6m1uQOEw"] = ["Service Dependencies","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_dependencies_5003740.html"];
contentPage.processPage.elementUrls["_f4FaYekLEd-IPpFA2ds-HA"] = ["DEVELOP and Agree to Client Solution","process.tech.teamsd.base-ibm_int/deliveryprocesses/develop_and_agree_to_client_solution_54C3D910.html"];
contentPage.processPage.elementUrls["_XvBcAMZAEd2iyfx7rQCA8A"] = ["Service Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_model_1E2FB879.html"];
contentPage.processPage.elementUrls["_x09L9r1IEdyrVscmNb_pGw"] = ["Understand Business Environment and Objectives","process.tech.teamsd.base-ibm_int/deliveryprocesses/understand_business_environment_F6F6114F.html"];
contentPage.processPage.elementUrls["_NpOhQP4kEeSlbqNAhOaBVQ"] = ["Subject Matter Expert","process.tech.teamsd.base-ibm_int/deliveryprocesses/subject_matter_expert_E2BDB8EE.html"];
contentPage.processPage.elementUrls["__KR7YG12Ed6A1OllLcra5Q"] = ["Estimation Report","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/est_report_9E09C789.html"];
contentPage.processPage.elementUrls["_LX0Vkos2Ed2OXeRvRIcs3A"] = ["Standards","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/standards_862167F6.html"];
contentPage.processPage.elementUrls["_fwpRUcEXEea7yN6m1uQOEw"] = ["Actor","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/actor_A93FE1A9.html"];
contentPage.processPage.elementUrls["_Xns0qt2kEdy-jeg0wYuB9Q"] = ["Standards","process.tech.teamsd.base-ibm_int/deliveryprocesses/standards_C3C99B4C.html"];
contentPage.processPage.elementUrls["_Xns0pN2kEdy-jeg0wYuB9Q"] = ["Candidate Asset List","process.tech.teamsd.base-ibm_int/deliveryprocesses/candidate_asset_list_600C507.html"];
contentPage.processPage.elementUrls["_evUr8L1VEdyrVscmNb_pGw"] = ["Evaluate Success","process.tech.teamsd.base-ibm_int/deliveryprocesses/evaluate_success_1C35DCDA.html"];
contentPage.processPage.elementUrls["_gVz-Eb1UEdyrVscmNb_pGw"] = ["Operational Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/operational_model_31C06A16.html"];
contentPage.processPage.elementUrls["_r0U7sb1HEdyrVscmNb_pGw"] = ["Team Solution Design","process.tech.teamsd.base-ibm_int/deliveryprocesses/teamsd_6B210FD9.html"];
contentPage.processPage.elementUrls["_Xns0od2kEdy-jeg0wYuB9Q"] = ["Architectural Decisions","process.tech.teamsd.base-ibm_int/deliveryprocesses/architectural_decisions_3007F6FE.html"];
contentPage.processPage.elementUrls["_C3JAcN5MEdy-jeg0wYuB9Q"] = ["Project Definition","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/proj_definition_C6C3B447.html"];
contentPage.processPage.elementUrls["_cPsHoN5NEdy-jeg0wYuB9Q"] = ["Technical Solution Architect","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/technical_solution_architect_4E14DCF7.html"];
contentPage.processPage.elementUrls["_C2_PcN5MEdy-jeg0wYuB9Q"] = ["Technical Solution Architect","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/technical_solution_architect_C76D0EE0.html"];
contentPage.processPage.elementUrls["_IeUVcNtVEeG14pvxQP-BKw"] = ["Client Imperative","process.tech.teamsd.base-ibm_int/deliveryprocesses/client_imperative_30A19D91.html"];
contentPage.processPage.elementUrls["_R4SPUHswEd6qiI9bUPa0dA"] = ["Use-Case Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/use_case_model_6FACA7FF.html"];
contentPage.processPage.elementUrls["_N9Ypov3zEeSZ9oW5ZnQ6AA"] = ["Architecture Overview","process.tech.teamsd.base-ibm_int/deliveryprocesses/architecture_overview_61A80143.html"];
contentPage.processPage.elementUrls["_lh6Qgb1JEdyrVscmNb_pGw"] = ["DEVELOP and Agree to Client Solution","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/develop_and_agree_to_client_solution_5909977E.html"];
contentPage.processPage.elementUrls["_wQzWsMLcEdyILIjfj0O0vQ"] = ["Identify Opportunity","process.tech.teamsd.base-ibm_int/deliveryprocesses/identify_opportunity_5CDF3651.html"];
contentPage.processPage.elementUrls["_tzWE4v4PEeSYqfYP0mAopw"] = ["User Interface Prototype","process.tech.teamsd.base-ibm_int/deliveryprocesses/ui_prototype_C877F775.html"];
contentPage.processPage.elementUrls["_WJFoZMXREeaaG61gY1NekQ"] = ["Zone Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/zone_model_33B026A2.html"];
contentPage.processPage.elementUrls["_JwTtgDQIEd2uMvBh-GQtOw"] = ["Estimation Report","process.tech.teamsd.base-ibm_int/deliveryprocesses/est_report_FC40E377.html"];
contentPage.processPage.elementUrls["_ffvQUWEBEd6dM5yVkA6IKQ"] = ["Account Profile","process.tech.teamsd.base-ibm_int/deliveryprocesses/account_profile_3D41625A.html"];
contentPage.processPage.elementUrls["_fwwmEcEXEea7yN6m1uQOEw"] = ["Service Specification","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_specification_6686EBAD.html"];
contentPage.processPage.elementUrls["_MlRwob1FEdyrVscmNb_pGw"] = ["EXPLORE Options and Approach","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/explore_options_and_approach_DB5B313F.html"];
contentPage.processPage.elementUrls["_gBcGYcEXEea7yN6m1uQOEw"] = ["Node","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/node_CD83AF1.html"];
contentPage.processPage.elementUrls["_gBg-4cEXEea7yN6m1uQOEw"] = ["Location","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/location_5EFBF858.html"];
contentPage.processPage.elementUrls["_LX0VkIs2Ed2OXeRvRIcs3A"] = ["Business Direction","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/business_direction_8CEA73D0.html"];
contentPage.processPage.elementUrls["_-d_J8AwfEeSQgZ4v5FkZyw"] = ["Sketch Initial Architecture Overview","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/sketch_initial_architecture_overview_7EA107AA.html"];
contentPage.processPage.elementUrls["_ap01QQD4Ed2JMcEzMiB9RQ"] = ["Project Manager","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/project_manager_D93303F3.html"];
contentPage.processPage.elementUrls["_wewUYG1xEd6d59QVK2kfQw"] = ["Estimation Report","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/est_report_920C1ABE.html"];
contentPage.processPage.elementUrls["_YfVxEr1UEdyrVscmNb_pGw"] = ["Architecture Overview","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/architecture_overview_58C5EBB3.html"];
contentPage.processPage.elementUrls["_EZkfQgD4Ed2JMcEzMiB9RQ"] = ["Component Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/component_model_F2993A69.html"];
contentPage.processPage.elementUrls["_EZkfQwD4Ed2JMcEzMiB9RQ"] = ["Architecture Overview","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/architecture_overview_FD371A79.html"];
contentPage.processPage.elementUrls["_sJW3kdxKEeSK_fH7qhcZdQ"] = ["Strategic Roadmap","process.tech.teamsd.base-ibm_int/deliveryprocesses/strategic_roadmap_34BD59C7.html"];
contentPage.processPage.elementUrls["_rEa4AMfZEd6U27gReX5GsQ"] = ["Use-Case Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/use_case_model_1E8E0076.html"];
contentPage.processPage.elementUrls["_e9hPkekLEd-IPpFA2ds-HA"] = ["EXPLORE Options and Approach","process.tech.teamsd.base-ibm_int/deliveryprocesses/explore_options_and_approach_FAAACAF1.html"];
contentPage.processPage.elementUrls["_X7ZEEMZAEd2iyfx7rQCA8A"] = ["Service Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_model_B4077A80.html"];
contentPage.processPage.elementUrls["_YfMnJb1UEdyrVscmNb_pGw"] = ["Develop Architecture Overview","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/develop_architecture_overview_F7A91B5D.html"];
contentPage.processPage.elementUrls["_gA_accEXEea7yN6m1uQOEw"] = ["Service Portfolio","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_portfolio_F2B8AEC4.html"];
contentPage.processPage.elementUrls["_bXqpFb1UEdyrVscmNb_pGw"] = ["Architectural Decisions","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/architectural_decisions_1DCE9E48.html"];
contentPage.processPage.elementUrls["_gBaRMcEXEea7yN6m1uQOEw"] = ["Zone Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/zone_model_DD10280A.html"];
contentPage.processPage.elementUrls["_7GyWor0zEealzs-Z6MLRQg"] = ["Use Case","process.tech.teamsd.base-ibm_int/deliveryprocesses/use_case_89D2C53E.html"];
contentPage.processPage.elementUrls["_5sXAQMLeEdyILIjfj0O0vQ"] = ["Opportunity Qualified","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/opportunit_qualified.teamethod_82E9A1A5.html"];
contentPage.processPage.elementUrls["_ZreOwDftEeSB1PVrkj9DGw"] = ["Opportunity Plan","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/opportunity_plan_D29BCE40.html"];
contentPage.processPage.elementUrls["_75k30IItEeCl4-fvcYwsfw"] = ["Harvest Assets","process.tech.teamsd.base-ibm_int/deliveryprocesses/harvest_assets_AB7D0A9E.html"];
contentPage.processPage.elementUrls["_EZkfRAD4Ed2JMcEzMiB9RQ"] = ["Technical Environment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/technical_environment_BDF42862.html"];
contentPage.processPage.elementUrls["_iY8TcL1UEdyrVscmNb_pGw"] = ["Refine Viability Assessment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/refine_viability_assessment_1C51CB4C.html"];
contentPage.processPage.elementUrls["_QGpxcAD4Ed2JMcEzMiB9RQ"] = ["Define Key Services","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/define_key_services_26B2C2BF.html"];
contentPage.processPage.elementUrls["_-HgDBr1FEdyrVscmNb_pGw"] = ["Architectural Decisions","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/architectural_decisions_C96F9430.html"];
contentPage.processPage.elementUrls["_EZkfRQD4Ed2JMcEzMiB9RQ"] = ["Subject Area Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/subject_area_model_C8920872.html"];
contentPage.processPage.elementUrls["_XenKEd2kEdy-jeg0wYuB9Q"] = ["Current Organization Description","process.tech.teamsd.base-ibm_int/deliveryprocesses/current_org_description_A9875BDF.html"];
contentPage.processPage.elementUrls["_msArIL1UEdyrVscmNb_pGw"] = ["Propose Solution, Resolve Concerns","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/propose_solution_resolve_concerns_C5C8ABB1.html"];
contentPage.processPage.elementUrls["_WJHdlMXREeaaG61gY1NekQ"] = ["Connection","process.tech.teamsd.base-ibm_int/deliveryprocesses/connection_FEE38643.html"];
contentPage.processPage.elementUrls["_cP_poN5NEdy-jeg0wYuB9Q"] = ["Project Definition","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/proj_definition_580F63B3.html"];
contentPage.processPage.elementUrls["_Xns0qd2kEdy-jeg0wYuB9Q"] = ["Operational Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/operational_model_B92BBB3C.html"];
contentPage.processPage.elementUrls["_Xocbg92kEdy-jeg0wYuB9Q"] = ["Project Definition","process.tech.teamsd.base-ibm_int/deliveryprocesses/proj_definition_3CB3431E.html"];
contentPage.processPage.elementUrls["_zbmsgAwdEeSQgZ4v5FkZyw"] = ["Survey Candidate Assets and Optimize Solution Approach","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/survey_candidate_assets_D9DD4EC5.html"];
contentPage.processPage.elementUrls["_fwoqQcEXEea7yN6m1uQOEw"] = ["Use Case","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/use_case_96F8592D.html"];
contentPage.processPage.elementUrls["_Xf5Q0L1VEdyrVscmNb_pGw"] = ["Transition to Implementation","process.tech.teamsd.base-ibm_int/deliveryprocesses/transition_to_implementation_E21B93FE.html"];
contentPage.processPage.elementUrls["_ap01QAD4Ed2JMcEzMiB9RQ"] = ["Develop Solution Estimates ","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/develop_solution_estimates_CE9523E3.html"];
contentPage.processPage.elementUrls["_FFz7Ib1VEdyrVscmNb_pGw"] = ["CONFIRM Client Value and Experience","process.tech.teamsd.base-ibm_int/deliveryprocesses/confirm_client_value_and_experience.teamethod_85BEC7CE.html"];
contentPage.processPage.elementUrls["_8O3ikNxKEeSK_fH7qhcZdQ"] = ["Ideation","process.tech.teamsd.base-ibm_int/deliveryprocesses/ideation_537D87EB.html"];
contentPage.processPage.elementUrls["_fwv_AcEXEea7yN6m1uQOEw"] = ["Service Dependencies","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_dependencies_2D4C3444.html"];
contentPage.processPage.elementUrls["_Y1CV0N_mEdy-jeg0wYuB9Q"] = ["Technical Solution Architect","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_solution_architect_DAE89DB4.html"];
contentPage.processPage.elementUrls["_s4IxwMLcEdyILIjfj0O0vQ"] = ["Describe Current IT Environment and Plans","process.tech.teamsd.base-ibm_int/deliveryprocesses/describe_current_it_environment_14B89666.html"];
contentPage.processPage.elementUrls["_xSqMob1HEdyrVscmNb_pGw"] = ["Plan","process.tech.teamsd.base-ibm_int/deliveryprocesses/plan_3B3D50B4.html"];
contentPage.processPage.elementUrls["_YfVxEb1UEdyrVscmNb_pGw"] = ["Non-Functional Requirements","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/nonfunctional_requirements_4E280BA3.html"];
contentPage.processPage.elementUrls["_CevwEL1GEdyrVscmNb_pGw"] = ["Conduct Viability Assessment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/conduct_viability_assessment_892F3.html"];
contentPage.processPage.elementUrls["_tzWE4f4PEeSYqfYP0mAopw"] = ["Sponsor Users Identified","process.tech.teamsd.base-ibm_int/deliveryprocesses/sponsor_users_identified_BDDA1765.html"];
contentPage.processPage.elementUrls["_gVz-EL1UEdyrVscmNb_pGw"] = ["Develop High Level Operational Model","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/develop_high_level_operational_model_43275600.html"];
contentPage.processPage.elementUrls["_kQcnoL1UEdyrVscmNb_pGw"] = ["Evaluate Integrated Solution","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/evaluate_integrated_solution_C6E91D85.html"];
contentPage.processPage.elementUrls["_C3u2UN5MEdy-jeg0wYuB9Q"] = ["Standards","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/standards_E1FC9E3B.html"];
contentPage.processPage.elementUrls["_Fvry8P30EeSZ9oW5ZnQ6AA"] = ["Industry Consultant","process.tech.teamsd.base-ibm_int/deliveryprocesses/industry_consultant_D9BCCB7F.html"];
contentPage.processPage.elementUrls["_gBTjgcEXEea7yN6m1uQOEw"] = ["Actor","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/actor_58A26675.html"];
contentPage.processPage.elementUrls["_CT16wAhTEeWYzsxDhZ1NIg"] = ["Define Project","process.tech.teamsd.base-ibm_int/deliveryprocesses/define_project_teamsd_6805EBDF.html"];
contentPage.processPage.elementUrls["_-lR3AMLeEdyILIjfj0O0vQ"] = ["Solution Agreed To","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/solution_agreed_to.teamethod_52956E.html"];
contentPage.processPage.elementUrls["_Xns0ot2kEdy-jeg0wYuB9Q"] = ["Architecture Overview","process.tech.teamsd.base-ibm_int/deliveryprocesses/architecture_overview_3AA5D70E.html"];
contentPage.processPage.elementUrls["_bPws8GAREd6qEfhQ_fSeXg"] = ["Identify Delivery Approach","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/identify_delivery_approach_5C275E75.html"];
contentPage.processPage.elementUrls["_Xns0pt2kEdy-jeg0wYuB9Q"] = ["Technical Environment","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_environment_FF37B92D.html"];
contentPage.processPage.elementUrls["_WJLH8cXREeaaG61gY1NekQ"] = ["Location","process.tech.teamsd.base-ibm_int/deliveryprocesses/location_1FBF546D.html"];
contentPage.processPage.elementUrls["_QGzicAD4Ed2JMcEzMiB9RQ"] = ["Requirements Matrix","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/rqmts_matrix_26096826.html"];
contentPage.processPage.elementUrls["_fwvX8cEXEea7yN6m1uQOEw"] = ["Service Portfolio","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/service_portfolio_A48294E6.html"];
contentPage.processPage.elementUrls["_Xns0pd2kEdy-jeg0wYuB9Q"] = ["Component Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/component_model_F499D91D.html"];
contentPage.processPage.elementUrls["_ffvQUmEBEd6dM5yVkA6IKQ"] = ["Opportunity Plan","process.tech.teamsd.base-ibm_int/deliveryprocesses/opportunity_plan_2BDA7670.html"];
contentPage.processPage.elementUrls["_bXqpFL1UEdyrVscmNb_pGw"] = ["Candidate Asset List","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/candidate_asset_list_2F358A32.html"];
contentPage.processPage.elementUrls["_-HgDBb1FEdyrVscmNb_pGw"] = ["Document Architectural Decisions","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/document_architectural_decisions_BED1B420.html"];
contentPage.processPage.elementUrls["_x09L8r1IEdyrVscmNb_pGw"] = ["Technical Environment","process.tech.teamsd.base-ibm_int/deliveryprocesses/technical_environment_32642F30.html"];
contentPage.processPage.elementUrls["_VBlIIMLjEdyILIjfj0O0vQ"] = ["Project Implemented","process.tech.teamsd.base-ibm_int/deliveryprocesses/project_implemented_93918234.html"];
contentPage.processPage.elementUrls["_gBlQUcEXEea7yN6m1uQOEw"] = ["Component Specification","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/component_specification_27E90D56.html"];
contentPage.processPage.elementUrls["_N9Ypof3zEeSZ9oW5ZnQ6AA"] = ["Client Imperative","process.tech.teamsd.base-ibm_int/deliveryprocesses/client_imperative_570A2133.html"];
contentPage.processPage.elementUrls["_IeUVcdtVEeG14pvxQP-BKw"] = ["Strategic Roadmap","process.tech.teamsd.base-ibm_int/deliveryprocesses/strategic_roadmap_1F3AB1A7.html"];
contentPage.processPage.elementUrls["_ZBfmcL1VEdyrVscmNb_pGw"] = ["Monitor Pilot and Early Implementation","process.tech.teamsd.base-ibm_int/deliveryprocesses/monitor_pilot_and_early_implementation_27514890.html"];
contentPage.processPage.elementUrls["_tzWE4P4PEeSYqfYP0mAopw"] = ["Empathy Map","process.tech.teamsd.base-ibm_int/deliveryprocesses/empathy_map_CF41034F.html"];
contentPage.processPage.elementUrls["_WJFoYcXREeaaG61gY1NekQ"] = ["Node Model","process.tech.teamsd.base-ibm_int/deliveryprocesses/node_model_5DB75899.html"];
contentPage.processPage.elementUrls["_C3lFUN5MEdy-jeg0wYuB9Q"] = ["Technical Environment","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/technical_environment_CE9BB7F8.html"];
contentPage.processPage.elementUrls["_nfeD8MLcEdyILIjfj0O0vQ"] = ["Describe Current Organization","process.tech.teamsd.base-ibm_int/deliveryprocesses/describe_current_organization_192CD60C.html"];
contentPage.processPage.elementUrls["_QGpxcQD4Ed2JMcEzMiB9RQ"] = ["Subject Matter Expert","practice.tech.presale_sol_design.base-ibm_int/capabilitypatterns/subject_matter_expert_3150A2CF.html"];
contentPage.processPage.elementUrls["_Xns0rt2kEdy-jeg0wYuB9Q"] = ["Project Definition","process.tech.teamsd.base-ibm_int/deliveryprocesses/proj_definition_885B7D6B.html"];
contentPage.processPage.elementUrls["_XenKEN2kEdy-jeg0wYuB9Q"] = ["Business Direction","process.tech.teamsd.base-ibm_int/deliveryprocesses/business_direction_BAEE47C9.html"];
contentPage.processPage.elementUrls["_VuARsI8lEd2tn4QxorRg1Q"] = ["Pre-sale Solution Design","process.tech.teamsd.base-ibm_int/deliveryprocesses/team_soln_dsgn_pre_sale_solution_design_421A435F.html"];
